### ISSUE TITLE
Provide Documentation on IntrospectionFragmentMatcher for Prismic Slices With Apollo / Apollo Link

### ISSUE THREAD

**Issue by rvnewolf** [prismicio/apollo-link-prismic#10]
# Issue Overview
I am currently using Prismic with GraphQL + Apollo on a Next.js application.

Things were going well until I started trying to query for my slices and got this error:

```
You are using the simple (heuristic) fragment matcher, but your queries contain union or interface types. Apollo Client will not be able to accurately map fragments. To make this error go away, use the `IntrospectionFragmentMatcher` as described in the docs: https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher
```

## Searching For A Solution

First, I checked out [the link mentioned in the error above](https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher) only to find that this is a dead link 🧟🧟🧟. Joy!!

After some Googling, I ended up at the REAL link I think the error was trying to send me to:
[https://www.apollographql.com/docs/react/data/fragments/#fragments-on-unions-and-interfaces](https://www.apollographql.com/docs/react/data/fragments/#fragments-on-unions-and-interfaces)

As a part of the solution, the docs referred me to a tool called `graphql-code-generator` to do the generation needed to fix this error. I gave it a go… the tool wasn’t working with Prismic though.

So I moved on to Apollo's next suggestion, which was to manually query the server to generate the introspection data needed to fix the error.

This also did not work with Prismic. 😢

## Getting Closer

After looking through Prismic docs, I discovered that queries to the `graphql` endpoint just get proxied to Prismic's JS API. This makes the issue significantly harder to fix since it seemed none of the off-the-shelf solutions could work with this setup.

After some Googling, I came across [a relevant issue](https://github.com/birkir/gatsby-source-prismic-graphql/issues/6) in the `gatsby-source-prismic-graphql` repo that requests Gatsby support for Prismic Slices to fix an error related to `IntrospectionFragmentMatcher `. The issue was closed and the support was successfully added! That's good news!

I then went to the codebase for `gatsby-source-prismic-graphql` to see if I could find what they implemented. And ultimately I found a file called [getInstrospectionQueryResultData.js](https://github.com/birkir/gatsby-source-prismic-graphql/blob/master/packages/gatsby-source-prismic-graphql/src/utils/getIntrospectionQueryResultData.ts). Yayy! This is getting us closer to a fix!

## Implementing a Fix 🔥🔥🔥

I took what I found in the linked file above, cleaned it up a bit, and combined it with what Apollo recommended in their docs. 

Here's the code I ended up with to successfully run the introspection query on Prismic and generate a `prismicIntrospectionResults.json` file

````
const fetch = require('node-fetch');
const fs = require('fs');
const restUrl = 'https://my-repo-name.cdn.prismic.io/api/v2';
const graphqlUrl = 'https://my-repo-name.prismic.io/graphql';
const resultsFileName = 'prismicIntrospectionResults';

fetch(`${restUrl}` )
	.then( response => response.json() )
	.then((data) => {

		const masterRef = data.refs.find((response) => response.id === 'master');
		if (! masterRef ) return;

		fetch( `${graphqlUrl}?query=%7B%20__schema%20%7B%20types%20%7B%20kind%20name%20possibleTypes%20%7B%20name%20%7D%20%7D%20%7D%20%7D`, {

			headers: {
				'prismic-ref': masterRef.ref,
			}

		})
		.then((result) => result.json())
		.then((result) => {

			try {

				// here we're filtering out any type information unrelated to unions or interfaces
				const filteredData = result.data.__schema.types.filter(
					type => type.possibleTypes !== null,
				);

				result.data.__schema.types = filteredData;

				writeFile( result.data );

			} catch (error) {
				console.log( error );
			}

	})

})
const writeFile = (data) => {

	fs.writeFileSync(`./${resultsFileName}.json`, JSON.stringify(data), error => {

		if (error) {

		  console.error('Error writing fragmentTypes file', error);

		} else {

		  console.log('Fragment types successfully extracted!');

		}

	});
}
````

## Wrapping Up

After this victory, I continued on to number 2 & 3 in the [Apollo Documentation on Fragments](https://www.apollographql.com/docs/react/data/fragments/#fragments-on-unions-and-interfaces). Those steps were implemented exactly as described. I ran my introspection query, then started my server AAAAANNNDDDDD.....

**🎉🎉🎉NO MORE ERRORS!!!🎉🎉🎉**

Plus now my slice data was coming over!  Woooooo!

To make life easier, I added the file to run from a `package.json` script and then set it to run before any other commands so that I always refetch fresh data every time I fire up/build the app.

```
"scripts": {
	"dev": "npm run generate-introspection; next dev",
	"build": "npm run generate-introspection; next build",
	"start": "npm run generate-introspection; next start",
	"generate-introspection": "node ./src/__utility__/prismicDataIntrospection.js"
}
```

## Final Thoughts

I plan on writing a blog post about this, but ultimately I feel like this solution should be something covered in the Prismic docs as I imagine this is an issue people run into with some regularity when working with slices.

If I can provide anything else that would be helpful, please let me know!

Thanks!

**Comment by alexknipfer** [comment]
Thank you! This was really helpful!

**Comment by annacollins85** [comment]
Thanks for that!

**Comment by Vishal1419** [comment]
@codingwithchris I have copy-pasted your code in a new file and then I tried to run it before starting the project. It does not work for me.

I am using client-side rendering. Can you suggest some fix?

**Comment by beelarr** [comment]
Super helpful and now linked in the [Prismic Community site](https://community.prismic.io/t/apollo-graphql-warning-heuristic-fragment-matching-going-on/791/6). Thank you!!!

**Comment by rvnewolf** [comment]
> @codingwithchris I have copy-pasted your code in a new file and then I tried to run it before starting the project. It does not work for me.
> 
> 
> 
> I am using client-side rendering. Can you suggest some fix?

@Vishal1419 do you have a link to your repo or a complete example of your implementation?

**Comment by madeleineostoja** [comment]
I saw the docs on this and they’re pretty solid! Would it make sense to publish the introspection builder as a little npm module though? Since outside of gatsby using Prismic’s graphql API with Apollo is an extremely common use case, and this is a lot of unintuitive boilerplate that can be abstracted away.

The interface could just be something like

```
prismic-introspect —repo [repoid] —out [filepath]
```

Or even just include it as an export in this package that users can consume in their own scripts if nothing else

**Comment by madeleineostoja** [comment]
Update: nevermind, whipped up one myself: [prismic-apollo-introspect](https://github.com/madeleineostoja/prismic-apollo-introspect).

Basic usage:

```sh
prismic-apollo-introspect --repo <repoId> --out <path>
```

Happy to transfer it to the Prismic team for ongoing maintenance, just hit me up. Also feel free to use this in the official docs! It would greatly simplify the process :)

**Comment by angeloashmore** [comment]
Awesome tool @madeleineostoja! As you mentioned, the Prismic docs explain how to fetch this data and provide to the Apollo client.

Docs: https://prismic.io/docs/technologies/introspection-fragment-matching-with-graphql

The GraphQL docs are being updated to use the latest version of `apollo-link-prismic`. While this is being done, I'll think more about how we can integrate some kind of automated tool, whether that means mentioning your tool or maybe even integrating it into `apollo-link-prismic`'s package directly (LMK if you're open to this! 🙂).

I'm going to close this issue for now since this is now documented, but please feel free to reply here if needed.
