### ISSUE TITLE
downloading/ preparing a schema

### ISSUE THREAD

**Issue by benliger1987** [prismicio/apollo-link-prismic#2]
If you're proxying requests through another graphql API is there a way to download the full Schema from your accounts repo?

**Comment by nanorepublica** [comment]
Better late than never...

There is no current builtin way to directly grab the schema file. However, given the introspection capabilities of graphql. It is possible to get a schema from the endpoint and convert it.

I was doing this myself and knocked up this quick node script: https://gist.github.com/nanorepublica/48ec69db23da173d56be56398800d010

**Comment by srenault** [comment]
Hello, thanks we're going to take a look at this!

**Comment by tylermcrobert** [comment]
If i can add any value or context to this issue, I'd love to be able to generate typescript types from Prismic. Having the power of slices means sometimes the development can become error prone which typescript helps out with greately.

**Comment by angeloashmore** [comment]
Hey everyone,

Here's a modified version of @nanorepublica's script to download a Prismic schema using the latest packages.

It requires `@apollo/client`, `apollo-link-prismic`, and `node-fetch` to be installed.

If you need to use a custom URL (such as through a proxy), you can pass a `uri` property to `createPrismicLink()`, just like you would with the Apollo client used in your app.

```typescript
const { buildClientSchema, printSchema } = require("graphql");
const { gql, ApolloClient, InMemoryCache } = require("@apollo/client/core");
const { createPrismicLink } = require("apollo-link-prismic");
const fetch = require("node-fetch");
const fs = require("fs");

const repositoryName = "your-repository-name";
const accessToken = "your-access-token";
const outputFile = "./prismic.graphql";

const client = new ApolloClient({
	link: createPrismicLink({
		repositoryName,
		accessToken,
		fetch,
	}),
	cache: new InMemoryCache(),
});

// Query taken from Insomnia API client
const introspectionQuery = gql`
	query IntrospectionQuery {
		__schema {
			queryType {
				name
			}
			mutationType {
				name
			}
			subscriptionType {
				name
			}
			types {
				...FullType
			}
			directives {
				name
				description
				locations
				args {
					...InputValue
				}
			}
		}
	}
	fragment FullType on __Type {
		kind
		name
		description
		fields(includeDeprecated: true) {
			name
			description
			args {
				...InputValue
			}
			type {
				...TypeRef
			}
			isDeprecated
			deprecationReason
		}
		inputFields {
			...InputValue
		}
		interfaces {
			...TypeRef
		}
		enumValues(includeDeprecated: true) {
			name
			description
			isDeprecated
			deprecationReason
		}
		possibleTypes {
			...TypeRef
		}
	}
	fragment InputValue on __InputValue {
		name
		description
		type {
			...TypeRef
		}
		defaultValue
	}
	fragment TypeRef on __Type {
		kind
		name
		ofType {
			kind
			name
			ofType {
				kind
				name
				ofType {
					kind
					name
					ofType {
						kind
						name
						ofType {
							kind
							name
							ofType {
								kind
								name
								ofType {
									kind
									name
								}
							}
						}
					}
				}
			}
		}
	}
`;

client
	.query({ query: introspectionQuery })
	.then(({ data }) => {
		const graphqlSchemaObj = buildClientSchema(data);
		const sdlString = printSchema(graphqlSchemaObj);

		fs.writeFileSync(outputFile, sdlString);

		console.info(
			`The Prismic GraphQL schema for "${repositoryName}" was saved to: ${outputFile}`,
		);
	})
	.catch((error) => {
		console.error(error);
	});
```

**Comment by angeloashmore** [comment]
@tylermcrobert With the schema output from the above script, you can generate TypeScript types using tools like [GraphQL Code Generator](https://www.graphql-code-generator.com/).

If you are using TypeScript with GraphQL, I highly recommend using that tool.
