### ISSUE TITLE
Use module behind with a stub (proxy)

### ISSUE THREAD

**Issue by dsumac** [prismicio/apollo-link-prismic#37]
I would like to use this module with an api stub.
However, because of this line, the url called is always a url of this domain `cdn.prismic.io`.
That makes external calls that I would like to stub by specifying another url.

Ex: 
I would like use this url `http://localhost:12345/prismic/cdn` , and my stub would respond.

Concerned code:
https://github.com/prismicio/apollo-link-prismic/blob/master/src/index.js#L47

**Comment by angeloashmore** [comment]
Hi @dsumac, this is now possible with `v1.1.0`.

You can provide an explicit `uri` and `apiEndpoint` string.

- `uri`: The GraphQL URL. If you do not provide a `uri` option, a `cdn.prismic.io` URL will be created for you using the `repositoryName` option.
- `apiEndpoint`: The Prismic Rest API V2 endpoint URL. If you do not provide an `apiEndpoint`, a `cdn.prismic.io` URL will be created for you using the `repositoryName` option.

To fully stub this Link, you would need to provide stub URLs for both options. If you have any questions, please let me know!

**Comment by dsumac** [comment]
Thanks a lot for your feedback
