### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by zfwf** [prismicio/apollo-link-prismic#9]
Hi there, is there typings for this available?

**Comment by AlexDunmow** [comment]
TypeScript typings would be incredibly useful. Most people should be using TS these days.

**Comment by alexburner** [comment]
+1 type definitions would be great. I'm using this as a patch:

### typings/apollo-link-prismic.d.ts
```ts
declare module "apollo-link-prismic" {
  export function PrismicLink(args: {
      uri: string; 
      accessToken?: string;
    }): any;
}

```

**Comment by AlexanderVishnevsky** [comment]
Any updates???

**Comment by lihbr** [comment]
Hey @AlexanderVishnevsky thanks for the bump, I'll update the product team about this enhancement, also if you feel up to submitting a PR to include those typings that would be more than welcome ☺️ Cheers!

**Comment by byseop** [comment]
> +1 type definitions would be great. I'm using this as a patch:
> 
> ### typings/apollo-link-prismic.d.ts
> ```ts
> declare module "apollo-link-prismic" {
>   export function PrismicLink(args: {
>       uri: string; 
>       accessToken?: string;
>     }): any;
> }
> ```

it worked. thx!

**Comment by angeloashmore** [comment]
Hey everyone,

`apollo-link-prismic` was recently updated to `v1.1.1` which is written in TypeScript. The `createPrismicLink()` (and deprecated `PrismicLink()`) functions include correct types.

Your queries will not be typed by this library, but you can use other tools like [GraphQL Code Generator](https://www.graphql-code-generator.com/) to do so.
